<script lang="ts">
import Snippet from './snippet.svelte';

const snippet = `<pre class="shiki snazzy-light" style="background-color:#f1f5f9;color:#565869" tabindex="0"><code><span class="line"><span style="color:#F767BB">import</span><span style="color:#ADB1C2"> {</span><span style="color:#565869"> makeCommander </span><span style="color:#ADB1C2">}</span><span style="color:#F767BB"> from</span><span style="color:#ADB1C2"> '</span><span style="color:#CF9C00">@thetinkerinc/commander</span><span style="color:#ADB1C2">'</span><span style="color:#ADB1C2">;</span></span>
<span class="line"><span style="color:#F767BB">import</span><span style="color:#ADB1C2"> {</span><span style="color:#565869"> error </span><span style="color:#ADB1C2">}</span><span style="color:#F767BB"> from</span><span style="color:#ADB1C2"> '</span><span style="color:#CF9C00">@sveltejs/kit</span><span style="color:#ADB1C2">'</span><span style="color:#ADB1C2">;</span></span>
<span class="line"><span style="color:#F767BB">import</span><span style="color:#565869"> auth </span><span style="color:#F767BB">from</span><span style="color:#ADB1C2"> '</span><span style="color:#CF9C00">./auth</span><span style="color:#ADB1C2">'</span><span style="color:#ADB1C2">;</span></span>
<span class="line"><span style="color:#F767BB">import</span><span style="color:#565869"> db </span><span style="color:#F767BB">from</span><span style="color:#ADB1C2"> '</span><span style="color:#CF9C00">./db</span><span style="color:#ADB1C2">'</span><span style="color:#ADB1C2">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#F767BB">export</span><span style="color:#F767BB"> const</span><span style="color:#565869"> AuthenticatedCommander </span><span style="color:#ADB1C2">=</span><span style="color:#09A1ED"> makeCommander</span><span style="color:#ADB1C2">(</span><span style="color:#F767BB">async</span><span style="color:#ADB1C2"> ({</span><span style="color:#565869"> event </span><span style="color:#ADB1C2">})</span><span style="color:#ADB1C2"> =></span><span style="color:#ADB1C2"> {</span></span>
<span class="line"><span style="color:#F767BB">	const</span><span style="color:#565869"> userId </span><span style="color:#ADB1C2">=</span><span style="color:#565869"> auth</span><span style="color:#ADB1C2">.</span><span style="color:#09A1ED">decode</span><span style="color:#ADB1C2">(</span><span style="color:#565869">event</span><span style="color:#ADB1C2">.</span><span style="color:#565869">cookies</span><span style="color:#ADB1C2">.</span><span style="color:#09A1ED">get</span><span style="color:#ADB1C2">(</span><span style="color:#ADB1C2">'</span><span style="color:#CF9C00">auth_token</span><span style="color:#ADB1C2">'</span><span style="color:#ADB1C2">));</span></span>
<span class="line"><span style="color:#F767BB">	const</span><span style="color:#565869"> user </span><span style="color:#ADB1C2">=</span><span style="color:#F767BB"> await</span><span style="color:#565869"> db</span><span style="color:#ADB1C2">.</span><span style="color:#09A1ED">getUser</span><span style="color:#ADB1C2">(</span><span style="color:#565869">userId</span><span style="color:#ADB1C2">);</span></span>
<span class="line"><span style="color:#F767BB">	if</span><span style="color:#ADB1C2"> (!</span><span style="color:#565869">user</span><span style="color:#ADB1C2">)</span><span style="color:#ADB1C2"> {</span></span>
<span class="line"><span style="color:#09A1ED">		error</span><span style="color:#ADB1C2">(</span><span style="color:#FF5C57">403</span><span style="color:#ADB1C2">,</span><span style="color:#ADB1C2"> '</span><span style="color:#CF9C00">You need to log in to perform this action</span><span style="color:#ADB1C2">'</span><span style="color:#ADB1C2">);</span></span>
<span class="line"><span style="color:#ADB1C2">	}</span></span>
<span class="line"><span style="color:#F767BB">	return</span><span style="color:#ADB1C2"> {</span></span>
<span class="line"><span style="color:#11658F">		userId</span><span style="color:#ADB1C2">:</span><span style="color:#565869"> user</span><span style="color:#ADB1C2">.</span><span style="color:#565869">id</span></span>
<span class="line"><span style="color:#ADB1C2">	};</span></span>
<span class="line"><span style="color:#ADB1C2">});</span></span></code></pre>`;
</script>

<Snippet title="commanders.ts" {snippet} />
